#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 13 11:30:23 2021

@author: cristiano
"""

import numpy as np
import os
import pandas as pd
import glob



#class optimiser:
def readPositions(planet_name,directory):
    filelist = sorted(glob.glob(os.path.join(setdir, './step-*.csv')))
    if len(filelist) != 365:
        raise Exception('The length of the input datafile is not 365!')
    trajectory = np.empty((0,3), float)
    for file in filelist:
        a = pd.read_csv(file, sep = '\s',engine='python')
        if a.columns[0] == '#X':
            a = pd.read_csv(file, sep = '\s',header=None,engine='python')
        planet_position = a[a.iloc[:,-1]==planet_name].iloc[:,0:3].to_numpy()
        trajectory = np.append(trajectory, planet_position, axis = 0)
    return trajectory
            
def computeError(positions,positions_ref):
    SSR = 0
    for i in range(365):
        for j in range(3):
            SSR += (positions[i,j]-positions_ref[i,j])**2
    return np.sqrt(SSR)


                
cwd = os.getcwd()
setdir = cwd + '/trajectories'                    
planet_name = 'mercury'

traj = readPositions(planet_name,setdir)

                